# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbonosRemisiones',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('nodocto', models.IntegerField(db_column='NoDocto')),
                ('noremision', models.IntegerField(db_column='NoRemision')),
                ('fecha', models.DateField(db_column='Fecha')),
                ('hora', models.TimeField(db_column='Hora')),
                ('monto', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
            ],
            options={
                'db_table': 'abonos_remisiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Acabados',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('proveedorno', models.IntegerField(db_column='ProveedorNo')),
                ('idacabados', models.CharField(max_length=40, db_column='idAcabados')),
                ('fechaalta', models.DateField(null=True, db_column='FechaAlta', blank=True)),
                ('fechabaja', models.DateField(null=True, db_column='FechaBaja', blank=True)),
                ('horaalta', models.TimeField(null=True, db_column='HoraAlta', blank=True)),
                ('horabaja', models.TimeField(null=True, db_column='HoraBaja', blank=True)),
            ],
            options={
                'db_table': 'acabados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('proveedorno', models.IntegerField(db_column='ProveedorNo')),
                ('almacen', models.SmallIntegerField(db_column='Almacen')),
                ('razonsocial', models.CharField(max_length=45, null=True, db_column='RazonSocial', blank=True)),
                ('direccion', models.CharField(max_length=45, null=True, db_column='Direccion', blank=True)),
                ('colonia', models.CharField(max_length=45, null=True, db_column='Colonia', blank=True)),
                ('ciudad', models.CharField(max_length=45, null=True, db_column='Ciudad', blank=True)),
                ('estado', models.CharField(max_length=45, null=True, db_column='Estado', blank=True)),
                ('pais', models.CharField(max_length=45, null=True, db_column='Pais', blank=True)),
                ('telefono1', models.CharField(max_length=15, db_column='Telefono1')),
                ('telefono2', models.CharField(max_length=15, db_column='Telefono2')),
                ('fax', models.CharField(max_length=15, null=True, db_column='Fax', blank=True)),
                ('celular', models.CharField(max_length=15, null=True, db_column='Celular', blank=True)),
                ('radio', models.CharField(max_length=15, null=True, db_column='Radio', blank=True)),
                ('direccionelectronica', models.CharField(max_length=100, null=True, db_column='DireccionElectronica', blank=True)),
                ('fechaalta', models.DateField(db_column='FechaAlta')),
                ('fechabaja', models.DateField(db_column='FechaBaja')),
            ],
            options={
                'db_table': 'almacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigoarticulo', models.CharField(max_length=16, db_column='CodigoArticulo')),
                ('fechaalta', models.DateField(db_column='FechaAlta')),
                ('fechabaja', models.DateField(db_column='FechaBaja')),
                ('pagina', models.CharField(max_length=6, null=True, blank=True)),
                ('pathfoto', models.CharField(max_length=150, null=True, db_column='PathFoto', blank=True)),
                ('idmarca', models.CharField(max_length=40, db_column='idMarca')),
                ('idestilo', models.CharField(max_length=40, db_column='idEstilo')),
                ('idcolor', models.CharField(max_length=40, db_column='idColor')),
                ('idacabado', models.CharField(max_length=40, db_column='idAcabado')),
                ('idmodelo', models.CharField(max_length=40, db_column='idModelo')),
                ('talla', models.CharField(max_length=12, null=True, blank=True)),
                ('precio', models.FloatField(null=True, blank=True)),
                ('catalogo', models.CharField(max_length=12, db_column='Catalogo')),
                ('costo', models.FloatField(null=True, blank=True)),
            ],
            options={
                'db_table': 'articulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('asociadono', models.IntegerField(db_column='AsociadoNo')),
                ('razonsocial', models.CharField(max_length=45, null=True, db_column='RazonSocial', blank=True)),
                ('nombre', models.CharField(max_length=30, null=True, db_column='Nombre', blank=True)),
                ('appaterno', models.CharField(max_length=30, null=True, db_column='ApPaterno', blank=True)),
                ('apmaterno', models.CharField(max_length=30, null=True, db_column='ApMaterno', blank=True)),
                ('direccion', models.CharField(max_length=45, null=True, db_column='Direccion', blank=True)),
                ('colonia', models.CharField(max_length=45, null=True, db_column='Colonia', blank=True)),
                ('ciudad', models.CharField(max_length=45, null=True, db_column='Ciudad', blank=True)),
                ('estado', models.CharField(max_length=45, null=True, db_column='Estado', blank=True)),
                ('pais', models.CharField(max_length=45, null=True, db_column='Pais', blank=True)),
                ('telefono1', models.CharField(max_length=15, null=True, blank=True)),
                ('telefono2', models.CharField(max_length=15, null=True, blank=True)),
                ('fax', models.CharField(max_length=15, null=True, blank=True)),
                ('celular', models.CharField(max_length=15, null=True, blank=True)),
                ('radio', models.CharField(max_length=15, null=True, db_column='Radio', blank=True)),
                ('direccionelectronica', models.CharField(max_length=100, null=True, db_column='DireccionElectronica', blank=True)),
                ('fechaalta', models.DateField(db_column='FechaAlta')),
                ('fechabaja', models.DateField(db_column='FechaBaja')),
                ('pathfoto', models.CharField(max_length=150, null=True, db_column='PathFoto', blank=True)),
                ('sucursalno', models.SmallIntegerField(db_column='SucursalNo')),
                ('creditodisponible', models.FloatField(null=True, db_column='CreditoDisponible', blank=True)),
                ('nocontrol', models.CharField(max_length=12, null=True, db_column='NoControl', blank=True)),
                ('essocio', models.IntegerField(db_column='EsSocio')),
                ('forzarcobroanticipo', models.IntegerField(db_column='ForzarCobroAnticipo')),
            ],
            options={
                'db_table': 'asociado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=80)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(null=True, blank=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(unique=True, max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalogostatuspedidos',
            fields=[
                ('status', models.CharField(max_length=20, serialize=False, primary_key=True, db_column='Status')),
            ],
            options={
                'db_table': 'catalogostatuspedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalogostemporada',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('proveedorno', models.IntegerField(db_column='ProveedorNo')),
                ('periodo', models.SmallIntegerField(db_column='Periodo')),
                ('anio', models.SmallIntegerField(db_column='Anio')),
                ('clasearticulo', models.CharField(max_length=12, db_column='ClaseArticulo')),
                ('activo', models.TextField(db_column='Activo')),
            ],
            options={
                'db_table': 'catalogostemporada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Causasdevoluciones',
            fields=[
                ('causa', models.CharField(max_length=25, serialize=False, primary_key=True, db_column='Causa')),
            ],
            options={
                'db_table': 'causasdevoluciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprasdetalle',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('codigoarticulo', models.CharField(max_length=16, db_column='CodigoArticulo')),
                ('cantidadsolicitada', models.IntegerField(db_column='CantidadSolicitada')),
                ('costo', models.DecimalField(null=True, decimal_places=2, max_digits=8, db_column='Costo', blank=True)),
                ('pedidono', models.IntegerField(db_column='PedidoNo')),
                ('catalogo', models.CharField(max_length=12)),
                ('nolinea', models.IntegerField(db_column='NoLinea')),
            ],
            options={
                'db_table': 'comprasdetalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprasencab',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.SmallIntegerField(db_column='EmpresaNo')),
                ('proveedor', models.IntegerField(db_column='Proveedor')),
                ('almacen', models.SmallIntegerField(db_column='Almacen')),
                ('requisicionno', models.CharField(max_length=15, db_column='RequisicionNO')),
                ('fechacreacion', models.DateField(null=True, db_column='FechaCreacion', blank=True)),
                ('fechauitimamodificacion', models.DateField(null=True, db_column='FechaUItimaModificacion', blank=True)),
                ('horacraacion', models.TimeField(db_column='HoraCraacion')),
                ('horaultimamodificacion', models.TimeField(db_column='HoraUltimaModificacion')),
                ('usuariocreo', models.SmallIntegerField(db_column='UsuarioCreo')),
                ('usuariomodifico', models.SmallIntegerField(db_column='UsuarioModifico')),
                ('total', models.DecimalField(null=True, decimal_places=2, max_digits=8, db_column='Total', blank=True)),
            ],
            options={
                'db_table': 'comprasencab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('empresano', models.SmallIntegerField(serialize=False, primary_key=True, db_column='EmpresaNo')),
                ('ejerciciovigente', models.SmallIntegerField(db_column='EjercicioVigente')),
                ('periodovigente', models.SmallIntegerField(db_column='PeriodoVigente')),
                ('razonsocial', models.CharField(max_length=45, db_column='RazonSocial')),
                ('direccion', models.CharField(max_length=45, db_column='Direccion')),
                ('colonia', models.CharField(max_length=45, db_column='Colonia')),
                ('ciudad', models.CharField(max_length=45, db_column='Ciudad')),
                ('estado', models.CharField(max_length=45, db_column='Estado')),
                ('pais', models.CharField(max_length=45, db_column='Pais')),
                ('codigopostal', models.IntegerField(db_column='CodigoPostal')),
                ('telefono', models.CharField(max_length=15, db_column='Telefono')),
                ('rfc', models.CharField(max_length=16, db_column='RFC')),
                ('buzonelectronico', models.CharField(max_length=100, db_column='BuzonElectronico')),
                ('iva', models.FloatField(db_column='Iva')),
                ('porcentajeanticipo', models.FloatField(db_column='PorcentajeAnticipo')),
                ('tiposervidor', models.CharField(max_length=1, db_column='TipoServidor')),
                ('servidor', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('maxdiasextemp', models.SmallIntegerField(db_column='MaxDiasExtemp')),
                ('cuotadiasextemp', models.FloatField(db_column='CuotaDiasExtemp')),
                ('diasvigenciacredito', models.SmallIntegerField(db_column='DiasVigenciaCredito')),
                ('comisionporcalzadonorecogido', models.FloatField(db_column='ComisionPorCalzadoNoRecogido')),
                ('diasplazovmtoaquisocioconcred', models.SmallIntegerField(db_column='DiasPlazoVmtoAquiSocioConCred')),
                ('diasplazovmtoaquisociosincred', models.SmallIntegerField(db_column='DiasPlazoVmtoAquiSocioSinCred')),
                ('mostrarsocioenticket', models.TextField(null=True, db_column='MostrarSocioEnTicket', blank=True)),
            ],
            options={
                'db_table': 'configuracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Creditoaplicado',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('nodocto', models.IntegerField(db_column='NoDocto')),
                ('tipodedocumento', models.CharField(max_length=12, null=True, db_column='TipoDeDocumento', blank=True)),
                ('fechacreacion', models.DateField(db_column='FechaCreacion')),
                ('horacreacion', models.TimeField(db_column='HoraCreacion')),
                ('fechaultimamodificacion', models.DateField(db_column='FechaUltimaModificacion')),
                ('horaultimamodificacion', models.TimeField(db_column='HoraUltimaModificacion')),
                ('monto', models.DecimalField(null=True, decimal_places=2, max_digits=8, db_column='Monto', blank=True)),
            ],
            options={
                'db_table': 'creditoaplicado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Derechos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('descripcion', models.CharField(max_length=45, db_column='DESCRIPCION')),
                ('fechaalta', models.DateField(db_column='FechaAlta')),
                ('fechabaja', models.DateField(db_column='FechaBaja')),
            ],
            options={
                'db_table': 'derechos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devolucionesaprovheader',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.SmallIntegerField(db_column='EmpresaNo')),
                ('pedidono', models.IntegerField(db_column='PedidoNo')),
                ('almacen', models.IntegerField(db_column='Almacen')),
                ('fecha', models.DateField(db_column='Fecha')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, db_column='Total')),
            ],
            options={
                'db_table': 'devolucionesaprovheader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devolucionesaprovlines',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('devolucionno', models.IntegerField(db_column='DevolucionNo')),
                ('pedido', models.IntegerField(db_column='Pedido')),
                ('fechadevolucion', models.DateField(db_column='FechaDevolucion')),
                ('horadevolucion', models.TimeField(db_column='HoraDevolucion')),
                ('usuariocrea', models.SmallIntegerField(db_column='UsuarioCrea')),
                ('fechacreacion', models.DateField(db_column='FechaCreacion')),
                ('usuarionmodifica', models.SmallIntegerField(db_column='UsuarionModifica')),
                ('fechamodificacion', models.DateField(db_column='FechaModificacion')),
                ('productono', models.CharField(max_length=16, db_column='ProductoNo')),
                ('cantidadsolicitada', models.IntegerField(null=True, db_column='CantidadSolicitada', blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, db_column='Precio')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, db_column='Subtotal')),
                ('causadevolucion', models.CharField(max_length=25, db_column='CausaDevolucion')),
                ('catalogo', models.CharField(max_length=12, db_column='Catalogo')),
                ('nolinea', models.SmallIntegerField(db_column='NoLinea')),
            ],
            options={
                'db_table': 'devolucionesaprovlines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devolucionesheader',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pedidono', models.IntegerField(db_column='PedidoNo')),
                ('fecha', models.DateField(db_column='Fecha')),
                ('total', models.DecimalField(null=True, decimal_places=2, max_digits=8, db_column='Total', blank=True)),
            ],
            options={
                'db_table': 'devolucionesheader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devolucioneslines',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pedidono', models.IntegerField(db_column='PedidoNo')),
                ('fechadevolucion', models.DateField(db_column='FechaDevolucion')),
                ('horadevolucion', models.TimeField(db_column='HoraDevolucion')),
                ('usuariocrea', models.SmallIntegerField(db_column='UsuarioCrea')),
                ('fechacreacion', models.DateField(db_column='FechaCreacion')),
                ('usuarionmodifica', models.SmallIntegerField(db_column='UsuarionModifica')),
                ('fechamodificacion', models.DateField(db_column='FechaModificacion')),
                ('productono', models.CharField(max_length=16, db_column='ProductoNo')),
                ('cantidadsolicitada', models.IntegerField(null=True, db_column='CantidadSolicitada', blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, db_column='Precio')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, db_column='Subtotal')),
                ('causadevolucion', models.CharField(max_length=25, db_column='CausaDevolucion')),
                ('catalogo', models.CharField(max_length=12, db_column='Catalogo')),
                ('nolinea', models.SmallIntegerField(db_column='NoLinea')),
            ],
            options={
                'db_table': 'devolucioneslines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nodocto', models.IntegerField(db_column='NoDocto')),
                ('consecutivo', models.IntegerField(db_column='Consecutivo')),
                ('tipodedocumento', models.CharField(max_length=12, null=True, db_column='TipoDeDocumento', blank=True)),
                ('tipodeventa', models.CharField(max_length=12, db_column='TipoDeVenta')),
                ('fechacreacion', models.DateField(db_column='FechaCreacion')),
                ('horacreacion', models.TimeField(db_column='HoraCreacion')),
                ('usuarioquecreodcto_field', models.IntegerField(null=True, db_column='UsuarioQueCreoDcto.', blank=True)),
                ('fechaultimamodificacion', models.DateField(db_column='FechaUltimaModificacion')),
                ('horaultimamodificacion', models.TimeField(db_column='HoraUltimaModificacion')),
                ('usuariomodifico', models.IntegerField(null=True, db_column='UsuarioModifico', blank=True)),
                ('concepto', models.CharField(max_length=60, null=True, db_column='Concepto', blank=True)),
                ('monto', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('saldo', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('porcentajededescuento', models.FloatField(db_column='PorcentajeDeDescuento')),
                ('vtadecatalogo', models.TextField(db_column='VtaDeCatalogo')),
                ('cancelado', models.TextField(db_column='Cancelado')),
                ('comisiones', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('pagoaplicadoaremisionno', models.IntegerField(db_column='PagoAplicadoARemisionNo')),
                ('lo_recibido', models.DecimalField(null=True, decimal_places=2, max_digits=10, db_column='Lo_Recibido', blank=True)),
            ],
            options={
                'db_table': 'documentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentoscancelados',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('nodocto', models.IntegerField(db_column='NoDocto')),
                ('fechacancelacion', models.DateField(null=True, db_column='FechaCancelacion', blank=True)),
                ('horacancelacion', models.TimeField(null=True, db_column='HoraCancelacion', blank=True)),
                ('usuario', models.IntegerField(null=True, db_column='Usuario', blank=True)),
                ('motivo', models.CharField(max_length=100, null=True, blank=True)),
            ],
            options={
                'db_table': 'documentoscancelados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enviomailsaproveedor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresa', models.SmallIntegerField(db_column='Empresa')),
                ('enviono_field', models.IntegerField(db_column='EnvioNo.')),
                ('proveedor', models.IntegerField(db_column='Proveedor')),
                ('numalmacen', models.SmallIntegerField(db_column='NumAlmacen')),
                ('fecha', models.DateField(db_column='Fecha')),
                ('hora', models.TimeField(db_column='Hora')),
                ('buzondestinatarios', models.TextField(db_column='BuzonDestinatarios')),
                ('asunto', models.CharField(max_length=50, db_column='Asunto')),
                ('mensaj', models.TextField(db_column='Mensaj')),
                ('archivoanexo1', models.TextField(db_column='ArchivoAnexo1')),
                ('archivoanexo2', models.TextField(db_column='ArchivoAnexo2')),
            ],
            options={
                'db_table': 'enviomailsaproveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidoconfirmacion',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('numalmacen', models.SmallIntegerField(db_column='NumAlmacen')),
                ('fechasolicitud', models.DateField(db_column='FechaSolicitud')),
                ('fechatentativaconfirmacion', models.DateField(db_column='FechaTentativaConfirmacion')),
                ('status', models.CharField(max_length=15, null=True, blank=True)),
                ('nolinea', models.IntegerField(db_column='NoLinea')),
            ],
            options={
                'db_table': 'pedidoconfirmacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidoscancelados',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('pedido', models.IntegerField(db_column='Pedido')),
                ('productono', models.CharField(max_length=16, db_column='productono')),
                ('catalogo', models.CharField(max_length=12)),
                ('nolinea', models.IntegerField(db_column='NoLinea')),
                ('motivo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pedidoscancelados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidosheader',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pedidono', models.IntegerField(db_column='PedidoNo')),
                ('fechapedido', models.DateField(db_column='FechaPedido')),
                ('horapedido', models.TimeField(null=True, db_column='HoraPedido', blank=True)),
                ('saldototal', models.DecimalField(null=True, decimal_places=2, max_digits=8, db_column='Saldototal', blank=True)),
                ('vtatotal', models.DecimalField(null=True, decimal_places=2, max_digits=8, db_column='VtaTotal', blank=True)),
                ('usuariocrea', models.IntegerField(null=True, db_column='UsuarioCrea', blank=True)),
                ('fechaultimamodificacion', models.DateField(db_column='FechaUltimaModificacion')),
                ('fechacreacion', models.DateField(db_column='FechaCreacion')),
                ('horacreacion', models.TimeField(null=True, db_column='HoraCreacion', blank=True)),
                ('horamodicacion', models.TimeField(null=True, db_column='HoraModicacion', blank=True)),
                ('usuariomodifica', models.IntegerField(null=True, db_column='UsuarioModifica', blank=True)),
                ('idsucursal', models.IntegerField(db_column='idSucursal')),
                ('tiposervicio', models.CharField(max_length=20)),
                ('viasolicitud', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'pedidosheader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidoslines',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cantidadsolicitada', models.IntegerField(null=True, db_column='CantidadSolicitada', blank=True)),
                ('precio', models.DecimalField(null=True, max_digits=8, decimal_places=2, blank=True)),
                ('subtotal', models.DecimalField(null=True, max_digits=8, decimal_places=2, blank=True)),
                ('saldo', models.DecimalField(null=True, max_digits=8, decimal_places=2, blank=True)),
                ('status', models.CharField(max_length=15, null=True, db_column='Status', blank=True)),
                ('remisionno', models.IntegerField(db_column='RemisionNo')),
                ('nonotacreditoporpedido', models.IntegerField(db_column='NoNotaCreditoPorPedido')),
                ('nonotacreditopordevolucion', models.IntegerField(db_column='NoNotaCreditoPorDevolucion')),
                ('norequisicionaproveedor', models.IntegerField(db_column='NoRequisicionAProveedor')),
                ('nonotacreditopordiferencia', models.IntegerField(db_column='NoNotaCreditoPorDiferencia')),
                ('nolinea', models.IntegerField(db_column='NoLinea')),
                ('plazoentrega', models.IntegerField()),
                ('opcioncompra', models.CharField(max_length=15, db_column='OpcionCompra')),
                ('fechamaximaentrega', models.DateField(db_column='FechaMaximaEntrega')),
            ],
            options={
                'db_table': 'pedidoslines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidoslinesdocumentos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('pedido', models.IntegerField(db_column='Pedido')),
                ('productono', models.CharField(max_length=16, db_column='ProductoNo')),
                ('cantidadpendiente', models.IntegerField(db_column='CantidadPendiente')),
            ],
            options={
                'db_table': 'pedidoslinesdocumentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidoslinestemporada',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('pedido', models.IntegerField(db_column='Pedido')),
                ('productono', models.CharField(max_length=16, db_column='ProductoNo')),
                ('catalogo', models.CharField(max_length=12)),
                ('nolinea', models.IntegerField(db_column='NoLinea')),
                ('temporada', models.IntegerField(db_column='Temporada')),
            ],
            options={
                'db_table': 'pedidoslinestemporada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidosStatusFechas',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('status', models.CharField(max_length=15, db_column='Status')),
                ('fechamvto', models.DateField(null=True, db_column='FechaMvto', blank=True)),
                ('horamvto', models.TimeField(null=True, db_column='HoraMvto', blank=True)),
                ('usuario', models.IntegerField(null=True, db_column='Usuario', blank=True)),
            ],
            options={
                'db_table': 'pedidos_status_fechas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodosentrega',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('periodo', models.CharField(max_length=30, null=True, blank=True)),
            ],
            options={
                'db_table': 'periodosentrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preciobase',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('proveedorid', models.IntegerField(db_column='ProveedorId')),
                ('temporada', models.IntegerField(db_column='Temporada')),
                ('costo', models.DecimalField(null=True, decimal_places=2, max_digits=8, db_column='Costo', blank=True)),
                ('precio', models.DecimalField(null=True, decimal_places=2, max_digits=8, db_column='Precio', blank=True)),
                ('fechacreacion', models.DateField(null=True, db_column='FechaCreacion', blank=True)),
                ('fechamodificacion', models.DateField(null=True, db_column='FechaModificacion', blank=True)),
                ('horacreacion', models.TimeField(null=True, db_column='HoraCreacion', blank=True)),
                ('horamodificacion', models.TimeField(null=True, db_column='HoraModificacion', blank=True)),
                ('usuariocreo', models.IntegerField(null=True, db_column='UsuarioCreo', blank=True)),
                ('usuariomodifico', models.IntegerField(null=True, db_column='UsuarioModifico', blank=True)),
                ('pagina', models.CharField(max_length=6, null=True, db_column='Pagina', blank=True)),
                ('estilo', models.CharField(max_length=40, db_column='Estilo')),
                ('idmarca', models.CharField(max_length=40)),
                ('idcolor', models.CharField(max_length=40)),
                ('talla', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'preciobase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preciosopcionales',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('proveedor', models.IntegerField(db_column='Proveedor')),
                ('temporada', models.SmallIntegerField(db_column='Temporada')),
                ('articuloid', models.CharField(max_length=16, db_column='ArticuloId')),
                ('tipoprecio', models.CharField(max_length=15, db_column='TipoPrecio')),
                ('precio', models.DecimalField(null=True, decimal_places=2, max_digits=8, db_column='Precio', blank=True)),
                ('fechacreacion', models.DateField(db_column='FechaCreacion')),
                ('horacreacion', models.TimeField(null=True, db_column='HoraCreacion', blank=True)),
                ('fechamodificacion', models.DateField(db_column='FechaModificacion')),
                ('horamodificacion', models.TimeField(null=True, db_column='HoraModificacion', blank=True)),
                ('catalogo', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'preciosopcionales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('proveedorno', models.IntegerField(db_column='ProveedorNo')),
                ('razonsocial', models.CharField(max_length=45, null=True, db_column='RazonSocial', blank=True)),
                ('direccion', models.CharField(max_length=45, null=True, db_column='Direccion', blank=True)),
                ('colonia', models.CharField(max_length=45, null=True, db_column='Colonia', blank=True)),
                ('ciudad', models.CharField(max_length=45, null=True, db_column='Ciudad', blank=True)),
                ('estado', models.CharField(max_length=45, null=True, db_column='Estado', blank=True)),
                ('pais', models.CharField(max_length=45, null=True, db_column='Pais', blank=True)),
                ('codigopostal', models.IntegerField(null=True, db_column='CodigoPostal', blank=True)),
                ('telefono1', models.CharField(max_length=15, null=True, blank=True)),
                ('telefono2', models.CharField(max_length=15, null=True, blank=True)),
                ('fax', models.CharField(max_length=15, null=True, blank=True)),
                ('cel', models.CharField(max_length=15, null=True, blank=True)),
                ('radio', models.CharField(max_length=15, null=True, blank=True)),
                ('email', models.CharField(max_length=100, null=True, blank=True)),
                ('fechaata', models.DateField(db_column='FechaAta')),
                ('fechabaja', models.DateField(db_column='FechaBaja')),
                ('usuarioquedioalta', models.SmallIntegerField(db_column='UsuarioQueDioAlta')),
                ('usuaroi', models.SmallIntegerField(db_column='Usuaroi')),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProveedorCatalogo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('idproveedor', models.IntegerField(db_column='idProveedor')),
                ('clasecatalogo', models.CharField(max_length=12, db_column='ClaseCatalogo')),
            ],
            options={
                'db_table': 'proveedor_catalogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Remisonesacredito',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('periodopago', models.SmallIntegerField(db_column='PeriodoPago')),
                ('a_nombre_de', models.CharField(max_length=35, db_column='A_nombre_de')),
            ],
            options={
                'db_table': 'remisonesacredito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requisicionheader',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('proveedor', models.IntegerField(db_column='Proveedor')),
                ('almacen', models.SmallIntegerField(db_column='Almacen')),
                ('requisicionno', models.IntegerField(db_column='RequisicionNO')),
                ('fechacreacion', models.DateField(null=True, db_column='FechaCreacion', blank=True)),
                ('fechauitimamodificacion', models.DateField(null=True, db_column='FechaUItimaModificacion', blank=True)),
                ('horacraacion', models.TimeField(db_column='HoraCraacion')),
                ('horaultimamodificacion', models.TimeField(db_column='HoraUltimaModificacion')),
                ('usuariocreo', models.SmallIntegerField(db_column='UsuarioCreo')),
                ('usuariomodifico', models.SmallIntegerField(db_column='UsuarioModifico')),
            ],
            options={
                'db_table': 'requisicionheader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requisicionlines',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cantidadsolicitada', models.IntegerField(db_column='CantidadSolicitada')),
                ('cantidadpendiente', models.IntegerField(db_column='CantidadPendiente')),
                ('requisicionquesustituye', models.IntegerField(db_column='RequisicionQueSustituye')),
                ('status', models.CharField(max_length=20, db_column='Status')),
                ('nolinea', models.IntegerField(db_column='NoLinea')),
            ],
            options={
                'db_table': 'requisicionlines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sociocatalogo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('idsocio', models.IntegerField(db_column='idSocio')),
                ('idproveedor', models.IntegerField(db_column='idProveedor')),
                ('clasecatalogo', models.CharField(max_length=12, db_column='ClaseCatalogo')),
                ('activo', models.TextField(db_column='Activo')),
            ],
            options={
                'db_table': 'sociocatalogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sociocatalogostemporada',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('asociadono', models.IntegerField(db_column='AsociadoNo')),
                ('activo', models.TextField(db_column='Activo')),
                ('nodocto', models.IntegerField()),
            ],
            options={
                'db_table': 'sociocatalogostemporada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.SmallIntegerField(db_column='EmpresaNo')),
                ('sucursalno', models.SmallIntegerField(db_column='SucursalNo')),
                ('direccion', models.CharField(max_length=45, null=True, db_column='Direccion', blank=True)),
                ('colonia', models.CharField(max_length=45, null=True, db_column='Colonia', blank=True)),
                ('ciudad', models.CharField(max_length=45, null=True, db_column='Ciudad', blank=True)),
                ('estado', models.CharField(max_length=45, null=True, db_column='Estado', blank=True)),
                ('pais', models.CharField(max_length=45, null=True, db_column='Pais', blank=True)),
                ('codigopostal', models.IntegerField(null=True, db_column='CodigoPostal', blank=True)),
                ('telefono1', models.IntegerField(null=True, db_column='Telefono1', blank=True)),
                ('telefono2', models.IntegerField(null=True, blank=True)),
                ('fax', models.IntegerField(null=True, db_column='Fax', blank=True)),
                ('celular', models.IntegerField(null=True, db_column='Celular', blank=True)),
                ('email', models.CharField(max_length=100, null=True, blank=True)),
                ('radio', models.CharField(max_length=15, null=True, blank=True)),
                ('fechaalta', models.DateField(db_column='FechaAlta')),
                ('fehabaja', models.DateField(db_column='FehaBaja')),
                ('iva', models.FloatField(db_column='Iva')),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiendaabastece',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('proveedorno', models.IntegerField(db_column='ProveedorNo')),
                ('tienda_no_field', models.IntegerField(db_column='Tienda_No.')),
                ('razonsocial', models.CharField(max_length=45, null=True, db_column='RazonSocial', blank=True)),
                ('direccion', models.CharField(max_length=45, null=True, db_column='Direccion', blank=True)),
                ('colonia', models.CharField(max_length=45, null=True, db_column='Colonia', blank=True)),
                ('ciudad', models.CharField(max_length=45, null=True, db_column='Ciudad', blank=True)),
                ('estado', models.CharField(max_length=45, null=True, db_column='Estado', blank=True)),
                ('pais', models.CharField(max_length=45, null=True, db_column='Pais', blank=True)),
                ('codigopostal', models.IntegerField(null=True, db_column='CodigoPostal', blank=True)),
                ('telefono1', models.IntegerField(null=True, db_column='Telefono1', blank=True)),
                ('telefono2', models.IntegerField(null=True, db_column='Telefono2', blank=True)),
                ('fax', models.IntegerField(null=True, db_column='Fax', blank=True)),
                ('cel', models.IntegerField(null=True, blank=True)),
                ('radio', models.CharField(max_length=15, null=True, blank=True)),
                ('email', models.CharField(max_length=100, null=True, blank=True)),
                ('fechaata', models.DateField(db_column='FechaAta')),
                ('fechabaja', models.DateField(db_column='FechaBaja')),
                ('usuarioquedioalta', models.SmallIntegerField(db_column='UsuarioQueDioAlta')),
                ('usuaroi', models.SmallIntegerField(db_column='Usuaroi')),
            ],
            options={
                'db_table': 'tiendaabastece',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposervicio',
            fields=[
                ('tiposervicio', models.CharField(max_length=20, serialize=False, primary_key=True)),
            ],
            options={
                'db_table': 'tiposervicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioDerechos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('derechono', models.IntegerField(db_column='DerechoNo')),
                ('activo_field', models.TextField(db_column='Activo?')),
            ],
            options={
                'db_table': 'usuario_derechos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empresano', models.IntegerField(db_column='EmpresaNo')),
                ('usuariono', models.IntegerField(db_column='UsuarioNo')),
                ('nombre', models.CharField(max_length=45, db_column='Nombre')),
                ('password', models.TextField(null=True, blank=True)),
                ('fechacreacion', models.DateField(db_column='FechaCreacion')),
                ('fechamodificacion', models.DateField(db_column='FechaModificacion')),
                ('activo', models.TextField(db_column='Activo')),
                ('nivel', models.IntegerField(db_column='Nivel')),
                ('usuario', models.CharField(unique=True, max_length=15, db_column='Usuario')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viasolicitud',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('descripcion', models.CharField(max_length=20, null=True, blank=True)),
            ],
            options={
                'db_table': 'viasolicitud',
                'managed': False,
            },
        ),
    ]
