from django.conf.urls import url
from pedidos import views
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete
urlpatterns = [
	url(r'^index/$',views.index,name='index'),
	url(r'^acceso/$',views.acceso,name='acceso'),
	url(r'^asociados/$',views.lista_asociados,name='lista_asociados'),
	url(r'^busca_pedidos/$',views.busca_pedidos,name='busca_pedidos'),
	url(r'^lista_pedidos/$',views.lista_pedidos,name='lista_pedidos'),
	url(r'^crea_pedidos/$',views.crea_pedidos,name='crea_pedidos'),
	url(r'^combo_temporadas/$',views.combo_temporadas,name='combo_temporadas'),
	url(r'^combo_catalogos/$',views.combo_catalogos,name='combo_catalogos'),
	url(r'^combo_estilos/$',views.combo_estilos,name='combo_estilos'),
	url(r'^combo_marcas/$',views.combo_marcas,name='combo_marcas'),
	url(r'^combo_colores/$',views.combo_colores,name='combo_colores'),
	url(r'^combo_tallas/$',views.combo_tallas,name='combo_tallas'),
	url(r'^grabar_pedidos/$',views.grabar_pedidos,name='grabar_pedidos'),
	url(r'^eli_reg_tmp/$',views.eli_reg_tmp,name='eli_reg_tmp'),
	url(r'^procesar_pedido/$',views.procesar_pedido,name='procesar_pedido'),
	url(r'^busca_socio/$',views.busca_socio,name='busca_socio'),
	url(r'^registro_socio/$',views.registro_socio,name='registro_socio'),
	url(r'^llena_combo_sucursal/$',views.llena_combo_sucursal,name='llena_combo_sucursal'),
	url(r'^logout_view/$',views.logout_view,name='logout_view'),
	url(r'^cambiar_password/$',views.cambiar_password,name='cambiar_password'),
	url(r'^reset/password_reset/$',password_reset,
		{'template_name':'pedidos/password_reset_form.html',
		'email_template_name':'pedidos/password_reset_email.html',
		'current_app':'pedidos','post_reset_redirect':'pedidos:password_reset_done'},
		name ='password_reset'),
	url(r'^reset/password_done/$',password_reset_done,
		{'template_name':'pedidos/password_reset_done.html','current_app':'pedidos'},
		name ='password_reset_done'),
	url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
		password_reset_confirm,
		{'template_name':'pedidos/password_reset_confirm.html',
		'current_app':'pedidos','post_reset_redirect' : 'pedidos:password_reset_complete'},
		name ='password_reset_confirm'),
	url(r'^reset/password_complete/$',password_reset_complete,
		{'template_name':'pedidos/password_reset_complete.html','current_app':'pedidos'},
		name ='password_reset_complete'),
	]